import MICROECONOMICS from "./MICROECONOMICS";
import PRINCIPLESOFMARKETING from "./PRINCIPLESOFMARKETING";
import COSTANDMANAGEMENTACCOUTING from "./COSTANDMANAGEMENTACCOUTING";

export default {
    micro_economics4 : MICROECONOMICS,
    principles_of_marketing4 : PRINCIPLESOFMARKETING,
    cost_and_management_accouting4 : COSTANDMANAGEMENTACCOUTING
}